### ISSUE TITLE
Use the architecture specific Apkindex for armhf and aarch64

### ISSUE THREAD

**Issue by lippl** [linuxserver/docker-mariadb#77]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Dockerfile uses the architecture specific Apkindex when building armhf and aarch64. 

## Current Behavior

When building the images without sepcifying the MARIADB_VERSION, the version is beeing querried from the Apkindex of the x86_64 architecture, independently from the actual architecture being built for.

## Steps to Reproduce

1. Build the image without specifying MARIADB_VERSION

## Environment
**OS:** any
**CPU architecture:** arm32/arm64
**How docker service was installed:**

**Comment by aptalca** [comment]
Why? They're not expected to be different. Afaik alpine doesn't have a mechanism to push different versions for different arches. Also, our ci triggers use the x86-64 repo to check for new builds and we match the dockerfiles to it.

**Comment by lippl** [comment]
Just in case the newer package version becomes unavailable in some architectures. In case the support is dropped, or they do not become available at the same time etc.
It seemed natural to query for the specific index when building for specific versions, as they make them available anyways...

**Comment by aptalca** [comment]
To be honest, it's one of those things that sure would look nice and proper, but is a zero sum game. In fact negative sum, because the next time we add/remove packages or make changes to the dockerfiles, we'll make the changes to the main `Dockerfile` and then copy/paste all the lines below line 1 (the FROM line that's arch specific) to the other dockerfiles. Different triggers would require more work for the maintainer. 

We don't expect there to ever be different versions for different arches in the alpine repo. If one arch gets dropped upstream, we'll probably have to deprecate it anyway, and a failed build will notify us of that.

The current situation with the ubuntu versions not being in sync across arches was a bad decision (poor compromise) on our part and one that we are working towards rectifying. It is also the only case among our 100+ images.

**Comment by lippl** [comment]
No worries, that is fine with me then :)
Your decissions based on your experience are well respected and your work very much appreciated!
